# Uncomment the next line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '9.0'

target 'WHoleWallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'BitcoinKit'
  pod 'KeychainAccess'
  pod 'CryptoSwift'
  pod 'Toast-Swift', '~> 4.0.0'
  pod 'SnapKit', '~> 4.2.0'
  pod 'IQKeyboardManagerSwift'
  pod 'MMPopupView'
  pod 'Alamofire'
  pod 'MJRefresh'
  pod 'XLPagerTabStrip'

  target 'WHoleWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WHoleWalletUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
